# Generated by Django 2.1.2 on 2018-10-26 16:37

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='')),
                ('pic', models.ImageField(upload_to='upload', verbose_name='')),
                ('adurl', models.URLField(verbose_name='')),
                ('adlocation', models.CharField(help_text='位置', max_length=2, verbose_name='位置')),
                ('status', models.CharField(default=1, help_text='状态', max_length=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('slug', models.SlugField(unique_for_year='', verbose_name='描述')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('status', models.CharField(help_text='状态', max_length=2, verbose_name='状态')),
                ('publish_date', models.DateTimeField(default=datetime.datetime(2018, 10, 26, 16, 37, 32, 532778), help_text='发布日期', verbose_name='发布日期')),
                ('expiration_date', models.DateTimeField(blank=True, help_text='有效日期', null=True, verbose_name='有效日期')),
                ('is_activate', models.BooleanField(blank=True, default=True, help_text='是否热门', verbose_name='是否热门')),
                ('picture', models.ImageField(help_text='图片', upload_to='upload', verbose_name='图片')),
                ('praise_num', models.IntegerField(default=0, help_text='点赞数', verbose_name='点赞数')),
                ('read_num', models.IntegerField(default=0, help_text='浏览数', verbose_name='浏览数')),
                ('fav_num', models.IntegerField(default=0, help_text='收藏数', verbose_name='收藏数')),
                ('author', models.ForeignKey(help_text='作者', on_delete=django.db.models.deletion.CASCADE, related_name='artical_author', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='大类', max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '新闻类别',
                'verbose_name_plural': '新闻类别',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='名称', max_length=20, verbose_name='名称')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 10, 26, 16, 37, 32, 531778), help_text='创建时间', verbose_name='创建时间')),
                ('completed', models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成')),
                ('categorys', models.ForeignKey(help_text='大类', on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='artical.Category')),
            ],
            options={
                'verbose_name': '新闻子栏目',
                'verbose_name_plural': '新闻子栏目',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('slug', models.SlugField(verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2018, 10, 26, 16, 37, 32, 533778), help_text='添加时间', verbose_name='添加时间')),
                ('articals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_artical', to='artical.Artical', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_user', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
            },
        ),
        migrations.AddField(
            model_name='artical',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artical_item', to='artical.Item', verbose_name=''),
        ),
        migrations.AddField(
            model_name='artical',
            name='tags',
            field=models.ForeignKey(blank=True, help_text='文章状态', on_delete=django.db.models.deletion.CASCADE, related_name='artical_tags', to='artical.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together={('user', 'articals')},
        ),
    ]
